/*globals define, _*/

/**
 * Generated by DecoratorGenerator
 */

define([
    'js/Decorators/DecoratorBase',
    './DiagramDesigner/PetriNetsDecorator.DiagramDesignerWidget',
    './PartBrowser/PetriNetsDecorator.PartBrowserWidget'
], function (
    DecoratorBase,
    PetriNetsDecoratorDiagramDesignerWidget,
    PetriNetsDecoratorPartBrowserWidget
) {

    'use strict';

    const DECORATOR_ID = 'PetriNetsDecorator';

    function PetriNetsDecorator(params) {
        const opts = _.extend({loggerName: this.DECORATORID}, params);

        DecoratorBase.apply(this, [opts]);

        this.logger.debug('PetriNetsDecorator ctor');
    }

    _.extend(PetriNetsDecorator.prototype, DecoratorBase.prototype);
    PetriNetsDecorator.prototype.DECORATORID = DECORATOR_ID;

    /*********************** OVERRIDE DecoratorBase MEMBERS **************************/

    PetriNetsDecorator.prototype.initializeSupportedWidgetMap = function () {
        this.supportedWidgetMap = {
            DiagramDesigner: PetriNetsDecoratorDiagramDesignerWidget,
            PartBrowser: PetriNetsDecoratorPartBrowserWidget
        };
    };

    return PetriNetsDecorator;
});
